### ISSUE TITLE
这个可以直接改数据集和标签格式来实现分割模型的蒸馏吗

### ISSUE THREAD

**Issue by RaZzzyz** [Hao840/OFAKD#1]
你好，我看了文章，发现这个蒸馏方法好像是针对图片分类的，可以通过数据格式的改变来进行对分割模型的蒸馏吗，因为我在文章和代码中都没有看到有关分割这方面的相关内容

**Comment by PotentialX** [comment]
理论上是可以的，全图丢进去做蒸馏估计会爆显存
