### ISSUE TITLE
An error of CRD

### ISSUE THREAD

**Issue by liguopeng0923** [Hao840/OFAKD#12]
Hi, @Hao840 ,

I miss an error when I run the codes for CRD.  Could you tell me the solutions?
<img width="1118" alt="image" src="https://github.com/Hao840/OFAKD/assets/61257834/3a91ca1d-1360-4cec-a06d-93f62cb8fd56">

**Comment by Hao840** [comment]
Hi @liguopeng0923, the bug has been fixed.
