### ISSUE TITLE
open discussions

### ISSUE THREAD

**Issue by liguopeng0923** [Hao840/OFAKD#13]
Hi, @Hao840 ,

I want to know if all the models in this paper are trained from scratch.
If yes, have you tried fine-tuning some existing student models with your method? Does it work?
If not, are there any other special operations?

The motivation for this question is that distilling existing teacher models into existing student models is more time-saving and practical.

**Comment by Hao840** [comment]
Hi @liguopeng0923,

All models in our paper were trained from scratch. 
While using a pretrained checkpoint to initialize the student model is time-saving, we believe that it can also mitigate the effect of different knowledge distillation approaches. Therefore, we trained all the models from scratch.
