### ISSUE TITLE
Architectures of swin-n and swin-p

### ISSUE THREAD

**Issue by liguopeng0923** [Hao840/OFAKD#17]
Hi @Hao840 ,

I cannot find the settings for swin-n and swin-p. Here are my implementations according to other papers. Is it correct?
<img width="1164" alt="image" src="https://github.com/Hao840/OFAKD/assets/61257834/f2fb6cc7-8d02-4399-accb-f085ac7fb6cc">

**Comment by Hao840** [comment]
Yes, they are the correct models, and they have been added into this repo now.

**Comment by liguopeng0923** [comment]
Thanks.
