### ISSUE TITLE
Different from your paper.

### ISSUE THREAD

**Issue by liguopeng0923** [Hao840/OFAKD#18]
Hi @Hao840 ,

I guess there may be some issues. You use **Deit**, **Mobilenetv2**, and **ResMLP** in your paper. But I only find **Beit** and **Mobilenetv1** in your codes.  Because I'm not familiar with their architecture, could you polish them or give me some instructions?

**Comment by Hao840** [comment]
Other models are defined in the timm library. You can check the available models by `timm.list_models()`

**Comment by liguopeng0923** [comment]
I mean that you do not provide the custom_forward or custom_model for Deit, Mobilenetv2, and ResMLP in this version.

**Comment by Hao840** [comment]
curtom_model defines the models not included in the timm. If they already exists, we direct use the versions in timm. The custom_forward method of all models used in the paper have already been implemented. Please check the code carefully.

**Comment by liguopeng0923** [comment]
Sorry, I can find them.
But why is the reported mobilenetv2_100 in imagenet 68.87 when the corresponding model in timm is 72.956?

**Comment by Hao840** [comment]
Performance of the model depends on the used training scheme. Our results are obtained by our configuration, which may be different from timm's.

**Comment by liguopeng0923** [comment]
OK, thanks.
