### ISSUE TITLE
How to finetune the teacher model for cifar100 based on pretrained checkpoints?

### ISSUE THREAD

**Issue by Death-void** [Hao840/OFAKD#29]
Hello, I dont know how to finetune the teacher model for cifar100 based on pretrained checkpoints.
Can u help me with that?

**Comment by Death-void** [comment]
i want to reproduce the results on cifar100, and i dont know the precise way to get the teacher model.

**Comment by Hao840** [comment]
Hi, teacher models for CIFAR-100 are finetuned from ImageNet checkpoints. You can refer to [this issue](https://github.com/Hao840/OFAKD/issues/14) for more details.

**Comment by Death-void** [comment]
Hi，i've already check this issue, still curious about how to finetune from ImageNet checkpoint. 
Can i do the finetune process by only modifying the config?

**Comment by Hao840** [comment]
You should use the manually delete `head.weight` and `head.bias` from the state dict and load the remaining into the student. Then, you can finetune the model using `--distiller vanilla`, which indicate KD is not adopted.

**Comment by Death-void** [comment]
can u give me the commandline config?

**Comment by Hao840** [comment]
Hi, we have released our [teacher models](https://github.com/Hao840/OFAKD/releases/tag/checkpoint-cifar100) on CIFAR100. Now you can direct use these models without fine-tuning by yourself.

**Comment by Nick32625** [comment]
thankyou very much!
