### ISSUE TITLE
Inquiry about CKA Implementation

### ISSUE THREAD

**Issue by WindFall-wyx** [Hao840/OFAKD#7]
Hello,

I've been exploring your work on model comparisons and I'm particularly interested in the Centered Kernel Alignment (CKA) method you've mentioned. 

Would it be possible for you to share the code snippet? Any additional guidance on using CKA with different neural network models would also be greatly appreciated.

Thank you for considering my request. I am looking forward to your response.

**Comment by Hao840** [comment]
Hi, please refer to [this link](https://github.com/google-research/google-research/tree/master/representation_similarity) for the CKA implementation.

**Comment by WindFall-wyx** [comment]
Thanks for your reply.
