### ISSUE TITLE
The function for mergering different patches for the vit students.

### ISSUE THREAD

**Issue by liguopeng0923** [Hao840/OFAKD#9]
Hi @Hao840 ,

I dont know The function for mergering different patches for the vit students to a fixed patch grids as following.

<img width="1256" alt="image" src="https://github.com/Hao840/OFAKD/assets/61257834/f4be110c-f6b9-411e-b948-07e014234c88">

**Comment by Hao840** [comment]
Hi @liguopeng0923,

The patch merging operation is meant to keep added branches lightweight. You can freely change this configuration, but a larger value could result in an OOM error.

**Comment by liguopeng0923** [comment]
Thanks for your timely reply!  I get it.
